### ISSUE TITLE
[12.17下午]电商3D购物-自研引擎探索和业务实践-沈彬(梓泷) 的文件克隆的时候报错

### ISSUE THREAD

**Issue by alphabetabc** [d2forum/17th#2]
[12.17下午]电商3D购物-自研引擎探索和业务实践-沈彬(梓泷)_杨舟(阿查) 
![image](https://user-images.githubusercontent.com/29876424/209418951-be30af3f-31da-48b4-8e28-38e9efd7a13a.png)

**Comment by cxfeng1** [comment]
Path 我改了下， 再试下
